apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deploy
spec:
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: mvcorsi/auth-service
        env:
          - name: MONGO_URI
            value: mongodb://auth-mongo-service:27017/auth
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: jwt-secret
                key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000


