name: deploy-manifests

on: 
  push:
    branches:
      - main
    paths:
      - 'infra/**'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:          
      - uses: actions/checkout@v2
      
      - name: Digital Ocean doctl install
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      
      - run: doctl kubernetes cluster kubeconfig save ticketing
      
      - name: Apply k8s
        run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
